### PR TITLE
Unit test for enum SerializableObjectWithState

### PR DESCRIPTION
**Pull request by tech-bash**
Fix: #774 
Add unit test for `serialization` and `deserialization` of enum ``SerializeableObjectWithState``.

### CODE REVIEW

**Comment by tech-bash** [comment]
I guess a review is required! or Is there something wrong on my part?

**Comment by Patrik-Stas** [comment]
hi @tech-bash there's some points to address before this can be merged:
- the tests are failing to compile, try to reproduce the CI issues locally and fix. 
- code formatting check is also failing, fix by running `cargo fmt`

**Comment by tech-bash** [comment]
Ok.

**Comment by tech-bash** [comment]
Closing because of cache error! Opening a new PR..

**Pull request closed without merging**
