### PR TITLE
fix(aries-vcx): fixed dependency listing in README for `Cargo.toml`

### PR DESCRIPTION
**Pull request by arminveres**
Using path does not work and crates from git sources need be specified through `git=...`.

### CODE REVIEW

**Comment by Patrik-Stas** [comment]
hi @arminveres thanks for the fix! 

By Hyperledger policy, all commits must be signed off (DCO) - which basically every commit message must contain following bottom line (example):
```
    Add integration test to nodejs wrapper
    
    Signed-off-by: Patrik Stas <patrik.stas@absa.africa>    
```

there's a switch in `git` to help you do this `--signoff`. You can fix your PR like this:
```
git commit --signoff --amend
```
and then push force the branch.

Thank you!

**Comment by Patrik-Stas** [comment]
@arminveres by the way, what we should probably also mention in the readme, it's highly recommended to fix the revision of the dependency, so you are not simply fetching the latest `main` branch (eg. adding `ver` field specification for the dependency in `cargo.toml`)

**Comment by arminveres** [comment]
Thanks @Patrik-Stas, I amended the commit and included a version tag. Should I be more verbose about it?

**Comment by Patrik-Stas** [comment]
@arminveres thanks for prompt DCO fix, but note that the example is currently not quite valid. `version` is not valid attribute when dealing with `git` dependencies - have a look at this https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories

>  You can combine the git key with the `rev`, `tag`, or `branch` keys

**Comment by arminveres** [comment]
I see, you are right, it built on my system, but it ignored the version tag and proceeded to use the latest tag available, so I didn't notice it. I adjusted the commit. Thanks!

**Comment by Patrik-Stas** [comment]
thanks @arminveres looks good, merging

By the way, I am curious to ask, are you looking to build some using `aries-vcx`, or are you yet just looking around? Let me know if you'd need some support; also we have discord and weekly community calls

**Comment by arminveres** [comment]
> Thanks @arminveres, looks good, merging.
> 
> By the way, I am curious to ask, are you looking to build some using `aries-vcx`, or are you yet just looking around? Let me know if you'd need some support; also we have discord and weekly community calls

Thanks!
I am working on my thesis and I am planning on using Aries, also possibly other parts of Hyperledger. I have already joined the discord. I will surely need support, its a tad overwhelming with so many repos and frameworks to go through! Thanks again!

**Pull request merged**
