### PR TITLE
(chore) update all cargo deps

### PR DESCRIPTION
**Pull request by gmulhearn**
updates all deps to latest, and ran a `cargo update`. Some exceptions:
* hyper in the did_resolver_web. 0.14->1.x.x is too breaking for me to deal with right now
* sqlx (locked due to aries-askar)
* legacy deps

### CODE REVIEW

**Comment by gmulhearn** [comment]
hopefully this quiets the dep bot ;)

**Review by JamesKEbert — APPROVED** [review]
LGTM!

**Comment by JamesKEbert** [comment]
Actually, looks like the checks might be failing..

**Comment by gmulhearn** [comment]
@JamesKEbert ah yep I missed a spot. Fixing shortly...

**Comment by JamesKEbert** [comment]
Something's not happy with the CI mediator check @gmulhearn -- I tried to rerun it, but same result I believe

**Comment by gmulhearn** [comment]
@JamesKEbert hopefully this fixes it, the mediator CI hasn't been ran in awhile, which is why we haven't encountered this; it was incorrectly trying to publish a release version of the image

**Review by JamesKEbert — APPROVED** [review]
Nice!

**Pull request merged**
