### PR TITLE
Bump peer dep node-vcx-wrapper to ~0.12.0

### PR DESCRIPTION
**Pull request by OoDeLally**

### CODE REVIEW

**Comment by Patrik-Stas** [comment]
@OoDeLally you need to sign off your commit. You can run 
```
git commit --amend --signoff
```
and the force push to fix it.

**Comment by OoDeLally** [comment]
Done

**Comment by OoDeLally** [comment]
@Patrik-Stas any idea with the tests fail?

**Comment by Patrik-Stas** [comment]
@OoDeLally It seems to me like some intermittent error, I've seen this at least once before but not sure why it happens. I've rerun CI

**Pull request closed without merging**
