### PR TITLE
Bump time to `0.3.20`

### LINKED ISSUE #795: Update `time` crate dependency to version 0.3.x
Info:
- We are using time `0.1.x`
- Latest version is `0.3.x`
- There's breaking changes between `0.1.x` and `0.2.x` (attempt for automatic update by dependabot fails https://github.com/hyperledger/aries-vcx/pull/792)
- Likely breaking changes between `0.2.x` and 0.3.x` as well

Task:
- Update `time` crate to latest version

### PR DESCRIPTION
**Pull request by swaptr**
This PR addresses the breaking changes in the `time` crate dependency.  
This PR aims to upgrade `time` to `0.3.20`.  
Fixes #795

### CODE REVIEW

**Comment by Patrik-Stas** [comment]
Thank you @swaptr! Let's wait for CI

**Comment by swaptr** [comment]
Thank you @Patrik-Stas for reviewing the PR. I think CI should work now. Also idk for some reason I am having trouble with signing commits, hence I have to squash and force push as a workaround. Until I fix this, I hope this is not a issue.

**Comment by Patrik-Stas** [comment]
Hi @swaptr seems like you've figured out the DCO. There's a failure in CI - test can't yet compile. 

Have a look please, seems like some additional tweak are required. You can easily verify the compilation locally 
```
 cargo check -F 'pool_tests agency_pool_tests'
 ```
and also
 ```
 cargo check -F 'general_test'
```
running these 2 command from root directory of the repo.

Thank you!

**Comment by Patrik-Stas** [comment]
hi @swaptr are you willing to further drive this PR to completion? It seems there's still some work outstanding
- resolve confilicts
- assure tests can be compiled and CI is passing

Additionally note we are now in bit of a freeze mode for couple day, waiting for https://github.com/hyperledger/aries-vcx/pull/787 to be completed. 
Perhaps it's best to wait for that to get merged and then proceed with addressing the points above.

**Comment by swaptr** [comment]
I am sorry for the delayed work on this PR. Thank you for your patience, although I did fix test compilations but as per your instructions I will update this PR once again after the freeze is over.

**Comment by swaptr** [comment]
@Patrik-Stas, I have fixed majority of the issues with this PR, but somehow the CI is still failing. I am out of ideas to fix this, can you look into this?

**Comment by Patrik-Stas** [comment]
hi @swaptr it's was a false positive failure. Not your fault, we'll have to tweak our CI to prevent this from happening on "from-fork" PRs

**Comment by Patrik-Stas** [comment]
Merged now :-) Thank you for contribution!

**Pull request merged**
