### PR TITLE
iOS Wrapper

### PR DESCRIPTION
**Pull request by PaulRps**
- Renamed ConnectMeVcx to VcxAPI
- Added type to parameters on function setLogger in VcxLogger
- Added/exposed new functions to VcxAPI (equalized like in wrappers/node/src/rustlib.ts) related to OOB, Proof, CredDef, Schema etc.
- Created VcxWrapperCallbacks.(h/m) to organize and reduce the code of VcxAPI (old ConnectMeVcx) file
- Organized some imports and cleaned some code
- Moved some type definitions from VcxAPI (old ConnectMeVcx) to VcxTypes
- Redefined VcxHandle type to be unsigned int
- Redefined type of all handles (connection, proof etc.) parameters on input and completion functions, in VcxAPI, to NSUInteger
- Replaced deprecated function vcx_connection_create_with_connection_request by vcx_connection_create_with_connection_request_v2 in libvcx.h and VcxAPI

### CODE REVIEW

**Comment by Patrik-Stas** [comment]
hi @PaulRps I didn't go trough it in detail, but reading through description it seem pretty cool! Give us a few days of time to catch up on these changes, but we'll get this in. 

Hi @kukgini can you also have a look at this PR and share what you think? Would be much appreciated!

**Comment by Patrik-Stas** [comment]
In the meantime @PaulRps , can you make sure your commits are signed off? The DCO check is failing https://github.com/hyperledger/aries-vcx/pull/663/checks?check_run_id=9694983151

For DCO check to pass, esentially every contain following construct: 
```
Signed-off-by: Your Name <your@email>
```
at the end of commit message, for example like on this commit here
https://github.com/hyperledger/aries-vcx/commit/34dba4738ecab351b6620f64a150770930400579
image

You can disregard failing 
```
CI / publish-docker-libvcx (pull_request) 
```
we'll have to fix our CI for this one

**Comment by PaulRps** [comment]
Hi @Patrik-Stas, i saw @kukgini's commit, i can wait to be merged and resolve conflicts later. The changes Kukgini did, i did too. So, about the commit signing i'll handle soon.

**Comment by Patrik-Stas** [comment]
@PaulRps oh I see!

However note, in the other comment I was referring to pomfar's commit https://github.com/hyperledger/aries-vcx/pull/656

**Comment by kukgini** [comment]
I beleive @PaulRps's PR is more desirable direction And reflecting more API changes that have been made in the meantime. My PR is just to hide some unnecessary exposure and convert handle to a more abstract data type (NSNumber). Anyway, I still think that It would be better to use NSNumber than NSUInteger. Is it ok that I drop my PR and make another PR based on @PaulRps's PR?

**Comment by PaulRps** [comment]
Hi guys, i just have fixed the commit signing error, i did not set my email in gpg key before, that was the problem. @kukgini i can change the type of handles to NSNumber, it's ok to me, in my flutter demo i'm using it.

**Comment by kukgini** [comment]
@PaulRps I dropped my PR. I would appreciate it if you could change the data type to NSNumber.

**Comment by PaulRps** [comment]
it's done, @kukgini.

**Review by Patrik-Stas — APPROVED** [review]

**Comment by Patrik-Stas** [comment]
Looks good to me @PaulRps this is nice cleanup and reorg!

**Pull request merged**
