### PR TITLE
Update CI Ubuntu to 20.0, rust to 1.55, add OOB to NodeJS wrapper

### PR DESCRIPTION
**Pull request by mirgee**
GitHub started [decommissioning](https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/) old Ubuntu 16.04 hosted runners. 

Also PRs:
https://github.com/hyperledger/aries-vcx/pull/347
https://github.com/hyperledger/aries-vcx/pull/353
were merged into this PR by an accident

Signed-off-by: Miroslav Kovar <miroslavkovar@protonmail.com>

### CODE REVIEW

**Review by Patrik-Stas — CHANGES_REQUESTED** [review]
This PR seems to contain some extra oob related commit.

Also I'd prefer explicitly stating version of ubuntu, I know it won't happen often but once they bump version of `latest`, we won't know something has changed, something will just break mysteriously.

**Comment by mirgee** [comment]
@Patrik-Stas 

> This PR seems to contain some extra oob related commit.

That's because a PR you merged was based on this one :)

> Also I'd prefer explicitly stating version of ubuntu, I know it won't happen often but once they bump version of latest, we won't know something has changed, something will just break mysteriously.

The logs contain the what OS version is used for the run. Also, the benefit of using `ubuntu-latest` is that there is no need to make a change once the current latest version is decommissioned again. But it's not a big deal.

**Comment by Patrik-Stas** [comment]
> That's because a PR you merged was based on this one :)

ohh sorry if merged in different order than indented, what do you suggest now? Probably have to reset the oob changed from this PR?  Though I am bit confused - if I merged something that was based on this one, the diff should not display the oob changes (assuming they are already contained in `main`)

**Comment by mirgee** [comment]
@Patrik-Stas All PRs you merged were merged into this one. I would just "Rebase and merge" this one.

**Comment by Patrik-Stas** [comment]
oooh I see, I've messed that up...gotta double check the base branch next time

**Pull request merged**
