### PR TITLE
Fix vdrproxy CI job intermittent failures

### PR DESCRIPTION
**Pull request by bobozaur**
Attempts to fix the vdrproxy CI job by adding a health check action for the services ports.
Additionally, within the same action and some other, the Rust toolchain version was hardcoded, therefore tweaked the inputs to accept the version for consistency reasons.

### CODE REVIEW

**Comment by Patrik-Stas** [comment]
looking at the logs from the fail container 
```
Listening on http://0.0.0.0:3030 ...
Error initializing pool: Pool timeout: Request was interrupted
```

it seems that the issue is that there's needs to be bit of timeout between the steps of starting indy pool and starting vdrproxy.

**Review by Patrik-Stas — CHANGES_REQUESTED** [review]
looking at the logs from the failed container 
```
Listening on http://0.0.0.0:3030 ...
Error initializing pool: Pool timeout: Request was interrupted
```

it seems that the issue is that there's needs to be bit of timeout between the steps of starting indy pool and starting vdrproxy.

**Comment by bobozaur** [comment]
> looking at the logs from the failed container
> 
> ```
> Listening on http://0.0.0.0:3030 ...
> Error initializing pool: Pool timeout: Request was interrupted
> ```
> 
> it seems that the issue is that there's needs to be bit of timeout between the steps of starting indy pool and starting vdrproxy.

Hmmm... Okay, so it's not the proxy itself. Where did you get the container logs, though?

**Comment by Patrik-Stas** [comment]
It's at the end of CI summary page, after scrolling through some CI warnings all the way down

image

**Review by Patrik-Stas — APPROVED** [review]

**Pull request merged**
