### PR TITLE
Use RwLock instead of Mutex in ObjectCache

### PR DESCRIPTION
**Pull request by Patrik-Stas**
- `ObjectCache` struct/implementation is used for library-wide global storage of vcx objects when using `aries-vcx` via FFI. The objects are identified by numeric "handle". These handles are keys to `map`, which is protected by `mutex` as there might be simultaneous calls into `aries-vcx` using this shared global data. Also each individual object inside the map is protected by `mutex`.
- Mutex assures there's only 1 write OR read at any point of time. Having `mutex` wrapping the map hence prevents for example creating new connection, if currently existing connection is being read to access some of its data. This can probably drive performance down rapidly in concurrent applications.

Signed-off-by: Patrik Stas <patrik.stas@absa.africa>

### CODE REVIEW

**Review by mirgee — COMMENTED** [review]
I suppose the reason for this change is safety and performance (to not block multiple readers) - however, it is not self-evident that `RwLock` is would be faster (although probable, since we expect more reads, I think)? It seems that it would depend on the target platform's implementation of `RwLock` algorithm...

**Comment by Patrik-Stas** [comment]
@mirgee good to think about unintended consequences, but I think even if RwLock is significantly slower than Mutex, the fact that read access to VCX Object of type X would block read accesses to all other objects of type X outweights any potential slowness of RwLocks.
I you look at implementation of any `update` method, for example disclosed proof:
```
HANDLE_MAP.get_mut(handle, |proof| {
   .. do stuff ..
  .. send something over network, synchronously ...
 }
```
This operation can take long time because it contains synchronous network and filesystem operations - and during this time, with Mutex any access to read information about other disclosed proofs are blocked

**Comment by mirgee** [comment]
> @mirgee good to think about unintended consequences, but I think even if RwLock is significantly slower than Mutex, the fact that read access to VCX Object of type X would block read accesses to all other objects of type X outweights any potential slowness of RwLocks.
> If you look at implementation of any `update` method, for example disclosed proof:
> 
> ```
> HANDLE_MAP.get_mut(handle, |proof| {
>    .. do stuff ..
>   .. send something over network, synchronously ...
>  }
> ```
> 
> This operation can take long time because it contains synchronous network and filesystem operations - and during this time, with Mutex any access to read information about other disclosed proofs are blocked

Agree

**Review by mirgee — DISMISSED** [review]

**Comment by mirgee** [comment]
> @mirgee good to think about unintended consequences, but I think even if RwLock is significantly slower than Mutex, the fact that read access to VCX Object of type X would block read accesses to all other objects of type X outweights any potential slowness of RwLocks.
> If you look at implementation of any `update` method, for example disclosed proof:
> 
> ```
> HANDLE_MAP.get_mut(handle, |proof| {
>    .. do stuff ..
>   .. send something over network, synchronously ...
>  }
> ```
> 
> This operation can take long time because it contains synchronous network and filesystem operations - and during this time, with Mutex any access to read information about other disclosed proofs are blocked

In this case, so would RwLock, but you are right,
```
HANDLE_MAP.get(handle, |proof| {
   .. do stuff ..
 }
```
blocks any other concurrent read access.

**Pull request merged**
