### PR TITLE
Use Status enums instead of u32

### PR DESCRIPTION
**Pull request by BulkBeing**
Solves #617 
Most of the changes are from VS code auto formatting.

### CODE REVIEW

**Comment by Patrik-Stas** [comment]
Hello @BulkBeing thank you! Let's see if CI passes, but looks good at first glance. Is this hacktoberfest contribution? :-)

**Review by Patrik-Stas — APPROVED** [review]

**Comment by Patrik-Stas** [comment]
@BulkBeing there's failures to compile unit and integration tests, can you please fix it?
You can build/run unit tests from root directory like this
```
RUST_TEST_THREADS=1 RUST_LOG=info cargo test --features general_test
```
and `aries-vcx` integration tests
```
cargo test -p aries-vcx --no-run --features "pool_tests agency_pool_tests mysql_test"
```

**Comment by Patrik-Stas** [comment]
Also please rebase on latest `main`, it will make your CI run somewhat faster

**Comment by BulkBeing** [comment]
@Patrik-Stas  Both 
```
RUST_TEST_THREADS=1 RUST_LOG=info cargo test --features general_test
cargo test -p aries-vcx --no-run --features "pool_tests agency_pool_tests mysql_test"
```
are passing on my local now.

**Comment by Patrik-Stas** [comment]
@BulkBeing awesome, let's wait for CI. I am not sure if something wrong with github, or we've run of some sort of per-repo computation minutes limit but it's terribly slow today.

**Comment by Patrik-Stas** [comment]
@mirgee our CI is not quite adjusted for fork PRs, seems like something to improve. Tested test manually, passing. I suggest we merge this and we can address CI for fork-based PRs after that.

I am just thinking perhaps we should run `cargo fmt` on main branch, then run it on this branch to loose the formatting delta here.

**Comment by Patrik-Stas** [comment]
@BulkBeing can you please run cargo fmt against the files (only those) you have modified? I think we are good to merge after that.

Thank you!

**Comment by BulkBeing** [comment]
@Patrik-Stas All the files I edited are already formatted (VS code format on save). Rechecked.

**Comment by Patrik-Stas** [comment]
@BulkBeing we've resolved some conflicts after we merged other PR. Merging this, thank you for contribution :-)

**Review by Patrik-Stas — APPROVED** [review]

**Review by mirgee — APPROVED** [review]

**Pull request merged**
