### PR TITLE
post_message migration [Issue #772]

### PR DESCRIPTION
**Pull request by Andy-Waine**
Resolves: Issue [#772](https://github.com/hyperledger/aries-vcx/issues/772) - Move out post_message to shared_vcx

###Short summary
-Migrated httpclient.rs file to `shared_vcx` directory
-The issue requested that the `post_message()` function be moved, but there were other items within httpclient.rs that `post_message()` depended upon.

### CODE REVIEW

**Comment by Patrik-Stas** [comment]
Hi @Andy-Waine thank you for contribution! We just created these "Good first issue" issues yesterday so it's great to see it reached you so quickly :-)  May I ask how did you run into this?

**Comment by Patrik-Stas** [comment]
Ah I see, that's very cool to hear!

About adressing the issue - it will be bit more work than just moving the file. As you can see, the CI is failing on stuff like 
```
error[E0425]: cannot find function `post_message` in module `httpclient`
  --> agency_client/src/internal/messaging.rs:13:21
```
as due to moving, the imports are now broken - you'll have to sync them up. Try to build the project locally before and after your changes and you should be able to reproduce the issue

**Comment by Andy-Waine** [comment]
I see - thank you for the heads up. I'll try building and working my way through the error logs. If I have questions, would it be best to post them on GitHub or the Discord server? @Patrik-Stas

**Comment by Patrik-Stas** [comment]
If it's directly about the pull request you have open, it's probably better to ask on the pull request itself as it gives us better context (about the changes you made etc)
But feel free to reach out on discord as well, if it doesn't require sending around big chunks of code

**Comment by Andy-Waine** [comment]
Hey @Patrik-Stas and dev team, I'm receiving the following error when running cargo run on my local machine's aries-vcx directory. I've tried deleting/renaming the file throwing the error, but my IDE and PowerShell terminal both display an error stating this action cannot be completed. Any Ideas? 😁

aries-vcx_build-err

**Comment by Andy-Waine** [comment]
I re-cloned the forked repo and tried again, but I'm receiving the following error regarding OpenSSL (which I've installed) and a similar error for libzmq. 😅 @Patrik-Stas @mirgee @gmulhearn 

```
--- stderr
  thread 'main' panicked at 'Unable to locate libzmq:
  Could not run `"pkg-config" "--libs" "--cflags" "libzmq" "libzmq >= 4.1"`
  The pkg-config command could not be found.

  Most likely, you need to install a pkg-config package for your OS.

  If you've already installed it, ensure the pkg-config command is one of the
  directories in the PATH environment variable.

  If you did not expect this build to link to a pre-installed system library,
  then check documentation of the zmq-sys crate for an option to
  build the library from source, or disable features or dependencies
  that require pkg-config.', C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\zmq-sys-0.11.0\build\pkg_config.rs:26:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `openssl-sys v0.9.78`
```

**Comment by Patrik-Stas** [comment]
hi @Andy-Waine you are missing `pkg-config`, follow this https://github.com/hyperledger/aries-vcx/blob/a1159bd476c0cc3f4f64bd26e2fcae4aee6a89fc/aries_vcx/TUTORIAL.md to assure you have all dependencies needed

**Comment by Andy-Waine** [comment]
@Patrik-Stas I think my fundamental issue is trying to do this on my work machine without the proper admin permissions. I'm going to try setting up the environment on my personal machine and report back. Thanks for your help!

**Comment by bobozaur** [comment]
@Andy-Waine I'm late to the party but I'd just like to redundantly outline the issue and the goal here.

There are a couple of places where the `HTTP_CLIENT` is being used. It was hastly copy pasted around to satisfy the need of a transport in various places (like `agency_client`, `libvcx`, etc).

Factoring this out into `shared_vcx` to be then imported and used by the other necessary crates would be the way to go. There are more refactors like this that need to be done to avoid code duplication and ensure consistency, so you're paving the way here :). Thanks for picking this up!

**Comment by Andy-Waine** [comment]
@bobozaur thank you for the outline!

I'm currently a little challenged on this one. I've tried three paths and I'm receiving errors on each:

1.) Moving httpclient.rs to a new directory (`/http`) within the `shared_vcx` directory. I've added references (Image Below) to the structs still being used that are within the `agency_client` directory, but I'm receiving an error that `agency_client` is an 'undeclared crate or module'. 
2.) Adding `agency_client` as a dependency of `shared_vcx` to resolve the error about undeclared crate/module. However since the latter is already a dependency of the former, I receive an error stating circular dependencies are not allowed.
3.) Prepending the struct references in the image below with 'crate::'. The error result is essentially the same as attempt 1.

Any tips on how I can clear these errors while referencing the structs still in `agency_client`?

cc: @Patrik-Stas 

image

**Comment by Andy-Waine** [comment]
Here's the git diff:

https://github.com/hyperledger/aries-vcx/compare/main...Andy-Waine:aries-vcx:main

**Comment by bobozaur** [comment]
> Any tips on how I can clear these errors while referencing the structs still in `agency_client`?

@Andy-Waine The simplest way would probably be to create some error type specific to the HTTP client, locally in the `shared_vcx` crate. Then the other crates can convert that error type to their own.

This is what I'd do at least, and I think it will suffice for the moment.

**Comment by Andy-Waine** [comment]
New PR: https://github.com/hyperledger/aries-vcx/pull/790

**Pull request closed without merging**
